apiVersion: v1
kind: Service
metadata:
  name: {{ include "teku-beacon.fullname" . }}-rpc
  labels:
    {{- include "teku-beacon.labels" . | nindent 4 }}
spec:
  ports:
    - port: 5051
      name: rpc
      targetPort: rpc
      protocol: TCP
  selector:
    {{- include "teku-beacon.selectorLabels" . | nindent 4 }}
  sessionAffinity: {{ .Values.service.rpc.sessionAffinity }}
  {{- if .Values.service.rpc.sessionAffinityConfig }}
  sessionAffinityConfig:
    {{- toYaml .Values.service.rpc.sessionAffinityConfig | nindent 4 }}
  {{- end }}
