apiVersion: v2
description: A Helm chart for running eth-validator-watcher
name: eth-validator-watcher
type: application
version: 1.0.0
maintainers:
  - name: Kiln
    email: contact@kiln.fi
    url: https://kiln.fi
  - name: Alluvial
    email: contact@alluvial.finance
    url: https://alluvial.finance
