apiVersion: v1
kind: Service
metadata:
  name: {{ include "geth.fullname" . }}-rpc
  labels:
    {{- include "geth.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.rpc.port }}
      name: http-rpc
      targetPort: http-rpc
      protocol: TCP
    - port: {{ .Values.service.ws.port }}
      name: ws-rpc
      targetPort: ws-rpc
      protocol: TCP
  {{- if .Values.jwtSecret }}
    - port: 8551
      name: engine
      targetPort: engine
      protocol: TCP
  {{- end }}
  selector:
    {{- include "geth.selectorLabels" . | nindent 4 }}
  sessionAffinity: {{ .Values.service.rpc.sessionAffinity }}
  {{- if .Values.service.rpc.sessionAffinityConfig }}
  sessionAffinityConfig:
    {{- toYaml .Values.service.rpc.sessionAffinityConfig | nindent 4 }}
  {{- end }}
