apiVersion: v1
kind: Service
metadata:
  name: {{ include "geth.fullname" . }}
  labels:
    {{- include "geth.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.rpc.port }}
      name: http-rpc
      targetPort: http-rpc
      protocol: TCP
    - port: {{ .Values.service.ws.port }}
      name: ws-rpc
      targetPort: ws-rpc
      protocol: TCP
  selector:
    {{- include "geth.selectorLabels" . | nindent 4 }}
